#~/.bashrc: executed by bash(1) for non-login shells

#aliases
alias lsl='ls -lFh'
alias lsa='ls -laFh'
alias top='top -u'

#Tools
alias getinfo='/Developer/Tools/GetFileInfo'
alias sees='sudo open -a /Applications/SubEthaEdit.app'
#Resets LaunchServices database - in Tiger removes the multiples of one ap showing up.
alias lsreg='/System/Library/Frameworks/ApplicationServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user /'
alias wkupdate='~/ShellScripts/nightly.sh'
alias screenback='/System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine -background &'
alias dud='du -h -d 1'
alias fmtreadme='cat $1 | fmt -w 95 | pbcopy'

#Functions
#Top 5 memory hogs
function memh() {
	top -n 5 -o rprvt -l1 | tail -n 5 | awk '{ printf "%5d\t%-10s\t%4.1fMB\n", $1, $2, $(NF-3) }';
}

#Back Up and date
function bkdate() {
	cp $1 $1.`date +%Y%m%d`;
}

#Display a dialog
function dialog() {
	osascript -e "tell application \"Finder\"" -e "activate" -e "display dialog \"$1\"" -e "end tell"
}

#Git revision number
function rgit() {
	git rev-list --abbrev-commit HEAD|wc -l|awk '{print $1}'
}

#Prompt
PS1='chealion@\w: '

#Information
date
