# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "trusty_dev"
    config.vm.box_url = "http://uec-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box"
    config.vm.network :private_network, ip: "192.168.123.126"
    
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
    config.vm.provision :shell, :path => "bootstrap.sh"
    #config.vm.provision :puppet do |puppet|
    #puppet.manifests_path = "manifests"
    #puppet.manifest_file  = "site.pp"
    #puppet.module_path = "modules_vagrant"
  #end
end
