#vagrant plugin install vagrant-openstack-plugin
#vagrant box add dummy https://github.com/cloudbau/vagrant-openstack-plugin/raw/master/dummy.box
# MUST RUN vagrant up --provider openstack
# Thanks Joe!

# Ubuntu 13.10: 55df6df8-27c3-4805-9a27-ef878f15e612
# Ubuntu 12.04: 4042220e-4f5e-4398-9054-39fbd75a5dd7
require 'vagrant-openstack-plugin'

servers = [
  'zfstest', 'zfstest2'
]
domain="mcjones.ca"

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  ssh_key = "cyberaMenlo"
  keypair = "mcjones-RAC"
  image = '55df6df8-27c3-4805-9a27-ef878f15e612'
  
  config.ssh.private_key_path = "~/.ssh/#{ssh_key}"

  # Basic OpenStack options
  # Note that an openrc file needs sourced before using
  config.vm.provider :openstack do |os|
    os.username        = ENV['OS_USERNAME']
    os.api_key         = ENV['OS_PASSWORD']
    os.tenant          = ENV['OS_TENANT_NAME']
    os.flavor          = /n1.small/
    os.image           = image
    os.endpoint        = "#{ENV['OS_AUTH_URL']}/tokens"
    os.keypair_name    = keypair
    os.ssh_username    = "ubuntu"
    os.security_groups = ['default','openstack']
  end
    shell_script = 'bootstrap.sh'
    # Loop through each server and define it
    servers.each do |server|
        fqdn = "#{server}.#{domain}"
        config.vm.define fqdn do |vm|

            # If there is a special bootstrap file for a server, use it
            # If not, use a generic bootstrap script
            if File.exists?("../bootstraps/#{server}-bootstrap.sh")
                shell_script = "../bootstraps/#{server}-bootstrap.sh"
            else
                shell_script = '../bootstraps/bootstrap.sh'
            end

            # Special options for utility
            if fqdn =~ /cic-utility/
                vm.vm.provider :openstack do |os|
                    os.flavor = /n1.small/
                end
            end
        end

        config.vm.provision 'shell', path: shell_script
        #config.vm.provision :puppet do |puppet|
        #  puppet.manifests_path = '../puppet/manifests'
        #  puppet.manifest_file = 'site.pp'
        #  puppet.module_path = '../puppet/modules'
        #end
    end
end
